### ISSUE TITLE
Len is sloppy

### ISSUE THREAD

**Issue by tegk** [niruix/sshwifty#1]
You are using a lot of 
`len(x) <= 0`

but why are you not using

`len(x) == 0` ?

**Comment by niruix** [comment]
They're the same. This is just some quirk thing I did.

`len(x) <= 0`, meaning I want/don't want everything that is larger than 0.

It's a mental marker, to help me understand my code later (Maybe years later).

**Comment by tegk** [comment]
`len(x) `can never be smaller than `0` so it would make sende to use `len(x) == 0`
using `len(x) <= 0` implies that it would be possible

**Comment by niruix** [comment]
Can I keep that just for peace of (my) mind? Please?
