### ISSUE TITLE
passphrase怎么添加

### ISSUE THREAD

**Issue by zhaoming0018** [niruix/sshwifty#13]
很好的项目，赞一个。
我在用的时候，使用私钥加密的ssh登陆方式时，没有找到关于passphrase的选项，就是指定私钥文件以后还需要一个密码，也就导致登陆失败了，请问这是功能上没有添加还是我没有发现呢？
还请指导，很想使用并学习这个项目，谢谢了

**Comment by niruix** [comment]
你需要先手动按照Sshwifty的提示解密指定的私钥，这是考虑到用户数据安全的原因有意设计成这样的，参考  #7：简单的说，就是我不希望用户有机会向这个软件提交自己私钥的Master Key，因为Master Key有可能比私钥本身还敏感。
