### ISSUE TITLE
预设的 Private Key 应该怎么填

### ISSUE THREAD

**Issue by loveqianool** [niruix/sshwifty#18]
docker 加载配置文件 Private Key 我直接复制粘贴报以下错误
```
 Copyright (C) Rui NI <nirui@gmx.com>
 https://github.com/niruix/sshwifty

[INF] Wed, 19 Feb 2020 17:59:10 UTC Sshwifty: Initializing
[INF] Wed, 19 Feb 2020 17:59:10 UTC Sshwifty > Configuration > Redundant: Loading configuration from: /sshwifty.conf.json
[WRN] Wed, 19 Feb 2020 17:59:10 UTC Sshwifty > Configuration > Redundant: Unable to load configuration from "File": invalid character '\n' in string literal
[ERR] Wed, 19 Feb 2020 17:59:10 UTC Sshwifty: "Redundant" loader cannot load configuration: All existing redundant loader has failed
[ERR] Wed, 19 Feb 2020 17:59:10 UTC Sshwifty: Unable to start due to error: All existing redundant loader has failed
[INF] Wed, 19 Feb 2020 17:59:10 UTC Sshwifty: Closed
```

我把 key 的换行全部删掉倒是能启动成功了，但是连接的时候找不到 key 。
```
Connection failed
ssh: handshake failed: ssh: no key found
```

**Comment by niruix** [comment]
不知道你的具体配置是什么样的，正确的值应该类似于：

    "-----BEGIN RSA PRIVATE KEY-----\nMIIEpQIBAAKCAQEAs1vnAk.....\n-----END RSA PRIVATE KEY-----"

也就是你把私钥文件一行一行粘贴到Sshwifty的配置文件里，然后用`\n`来替代换行。

注意：目前`sshwifty.conf.example.json`里的`--------- BEGIN RSA PRIVATE KEY ---------`其实是不正确的私钥头，正确的应该是`-----BEGIN RSA PRIVATE KEY-----`。

另外还要注意的是，“预设”功能其实只是一种*表单自动填充辅助*。**你在其中指定的值都会被发送给客户端，包括私钥**，以便客户端自动填写连接向导的表单。请自行评估这样做的安全性 :)

**Comment by loveqianool** [comment]
好的，如你所说的用 \n 替代换行后，成功启动并连接成功了。
我觉得这个应该写进文档，这样如我们这些小白用户才知道怎么配置。
当然，作为用户我会为我自己的行为负责 :) 谢谢你。

**Comment by niruix** [comment]
>  我觉得这个应该写进文档，这样如我们这些小白用户才知道怎么配置。

写文档的时候疏忽了，后面会给出正确的例子。
