### ISSUE TITLE
websocket错误 1006

### ISSUE THREAD

**Issue by countree103103** [niruix/sshwifty#20]
http error 403：to use a websocket interface ,a valid auth key must be provided.

用了https之后断开连接无法使用,请问怎么解决呢,谢谢

**Comment by countree103103** [comment]
我用的是0.21的

**Comment by countree103103** [comment]
"Servers": [
    {
      "ListenInterface": "0.0.0.0",
      "ListenPort": 8182,
      "InitialTimeout": 30,
      "ReadTimeout": 60,
      "WriteTimeout": 60,
      "HeartbeatTimeout": 20,
      "ReadDelay": 10,
      "WriteDelay": 10,
      "TLSCertificateFile": "/etc/crt/server_czy.pem",
      "TLSCertificateKeyFile": "/etc/crt/server_czy.key"    }
  ],

**Comment by niruix** [comment]
在正常情况下这个错误和HTTPS没有关系。

出现这个错误的原因可能是因为你修改了配置中的前端密码（即删除或添加了`SharedKey`），然后没有刷新前端页面导致的。

是否可以确认一下你是否修改了上述配置？

**Comment by countree103103** [comment]
> 
> 
> 在正常情况下这个错误和HTTPS没有关系。
> 
> 出现这个错误的原因可能是因为你修改了配置中的前端密码（即删除或添加了`SharedKey`），然后没有刷新前端页面导致的。
> 
> 是否可以确认一下你是否修改了上述配置？

我修改了SharedKey。

刚才测试了一下，在PC端chrome和firefox可以正常运行；
ios端的chrome，firefox，safari在清除所有cookie等之后尝试还是有同样的错误。
不知缘由为何？

**Comment by niruix** [comment]
怀疑可能是请求被缓存了，不过不太能确定，因为我没有iOS设备。

请试试看用其他的地址来访问，比如如果你之前通过主机名来访问Sshwifty，那么换用IP地址或域名来访问试试。

如果换用其他地址访问没有问题，而用旧的地址仍然会出现错误的话，那么几乎可以确定就是缓存导致的了。

**Comment by countree103103** [comment]
用ip和域名同样无法连接 如图
![1D268D97-C5EA-4297-9ACB-FA012C2E8947](https://user-images.githubusercontent.com/52630500/78524939-17a54500-7808-11ea-8e98-9b1f525b4e9e.png)

**Comment by niruix** [comment]
抱歉多次回复都没有能够确定问题，因为我没有设备能够自己测试。

请用iOS设备访问一下演示服务：https://sshwifty.herokuapp.com，看看是否可以正常连接？此外，你的证书是自签的么？

**Comment by countree103103** [comment]
演示服务正常。

这是我搭建服务的网址，您可以看看https://home.countree.cn:8182

证书是阿里云签发的。

**Comment by countree103103** [comment]
密码是11223344qq

**Comment by niruix** [comment]
就目前总结出来的信息，我可以大致推测：

1. 导致iOS出现问题的原因和`SharedKey`没有关系。只要配置了`SharedKey`，`A valid Auth Key must be provided`的日志信息在正常情况下也会产生，因为前端需要探测后端是否开启了密钥登陆。检测的方式是通过一个HTTP GET请求观察后端是否允许空密钥登陆，返回码403表示空密钥验证失败，这时前端会展示登录界面。
2. 由于iOS上的浏览器都不能正常使用，而PC端的则可以，我猜测可能是iOS系统的特性限制了Websocket连接。

我测试了一下你提供的实例，在Android上是可以访问的，但是证书的CN只包含裸域和`www`，访问的时候会提示证书错误，所以我猜测是不是由于证书导致了这些问题？

我还搜索了一下相关的信息，觉得iOS可能在WSS验证上做了一些限制。一篇文章 [Create a self-signed certificate for testing secure WebSockets in iOS or NodeJS](https://medium.com/himinds/create-a-self-signed-certificate-for-ios-or-nodejs-for-testing-secure-websockets-3df4bc722a3f) 里提到“These keys will work in a mobile app in an iOS environment, but you need to install the public key server.cert on your device”。另一个SO问题 [Secure WebSocket WSS (Self Signed Certificate) doesn't work on iOS Safari](https://stackoverflow.com/questions/57723263/secure-websocket-wss-self-signed-certificate-doesnt-work-on-ios-safari) 也提到“Adding the certificate manually into iOS can be one of the solution”。

我想询问一下你那边是否方便用一个合法的证书试一下？这大概是在目前已有信息的基础上我能给出的最好建议了。

**Comment by countree103103** [comment]
解决!更换合法证书后ios能成功访问！

**Comment by niruix** [comment]
问题解决了就好 :)
