### ISSUE TITLE
bind: cannot assign requested address

### ISSUE THREAD

**Issue by xingjiahui** [niruix/sshwifty#21]
作者您好！127.0.0.1:8182可以正常使用sshwifty，但我修改`/etc/sshwifty.conf.json`中的`ListenInterface`为我的ip地址就会报错，我想实现`ip:端口`访问是不是这样操作不对呀？
配置文件：
![](https://image.xingjiahui.top/blog/20200508214450.png)
报错信息：
![](https://image.xingjiahui.top/blog/20200508214659.png)

**Comment by niruix** [comment]
运行Sshwifty服务器端的计算机有图中所指的接口么？如果没有的话操作系统会拒绝程序的绑定申请。

你可以在服务器上运行命令 `ip a | grep "这里填写IP地址"` 或  `ifconfig | grep "这里填写IP地址"` 来确认所填写的接口是存在的。

**Comment by xingjiahui** [comment]
运行命令后无反应，那就应该是接口不存在。那我应该怎样做才能实现`ip:端口`访问？

**Comment by niruix** [comment]
那么你可以用`ip a`或者` ifconfig`命令查看系统里存在的接口，然后找到WAN上可以访问的，绑定那一个就可以了。

或者如果对安全没有顾虑，可以绑定`0.0.0.0`，这样操作系统会自动绑定所有可用接口。

**Comment by xingjiahui** [comment]
好的，感谢作者，解决了我的问题！

**Comment by xingjiahui** [comment]
实在是打扰作者了，我又把这个issues打开了，我现在遇到的问题是使用`ip:端口`可以运行sshwifty，但我也想实现像您的demo那样可以直接使用域名访问（因为想https访问只能绑定域名），我尝试Nginx反代，但我不知道root该填写什么，下面是我的配置文件，希望您给个思路。
![](https://image.xingjiahui.top/blog/20200509214702.png)
我是直接wget下载的release中linux的tar.gz包然后`sshwifty`运行的。

**Comment by niruix** [comment]
`ListenInterface`选项绑定的不是URL地址，而是本地网卡的IP地址。选项的值与实际访问的URL，比如`https://10.0.0.1:8182`并没有直接的对应关系。

`root`选项不是必须的。反向代理用`proxy_`这一系列选项就行了。可以参考下面的选项（你需要将一些设置改成适应自己运行环境的）：

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    upstream sshwifty_backend {
        server 127.0.0.1:8182; # 这里改成你Sshwifty后端的地址以及其监听的端口
        server 127.0.0.2:8182; # 如果你有其他后端实例，可以填写多个来进行负载均衡
    }

    server {
        listen ..... # 服务器的设置，这里省略，用你自己的就好

        # 下面的Location设置会将浏览器的页面和相关资源请求转发给后端
        location / {
            proxy_pass http://sshwifty_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }

        # 下面的Location与上面的类似，不同之处是它会转发Websocket需要用到的Connection和Upgrade头，并且强制使用HTTP/1.1连接（不会进行HTTP/2握手）。
        location /sshwifty/socket {
            proxy_pass http://sshwifty_backend;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
    }

另外：

1. 如果你在Sshwifty设置里指定了`HostName`，那么在反向代理的环境下就可以去掉了。因为Nginx会做相关的验证。
2. 如果你的Nginx与Sshwifty是运行在同一台服务器上的，并且两个进程可以通过Loopback（`127.0.0.1`）接口进行网络通讯，那么现在你可以将Sshwifty的`ListenInterface`选项设置成`127.0.0.1`，让Sshwifty仅监听在Loopback上。这样可以确保只有本地进程才能连接Sshwifty后端，而外部客户端则需要通过Nginx的中转来进行访问（假定外部客户端能够访问Nginx。根据你给出的配置，我猜你大概是想要达成这样的目的）。

**Comment by xingjiahui** [comment]
按照您给出的配置，我修改了nginx的配置信息，修改后使用`ip:8182`会出现下面的错误，也无法使用`webssh.xingjiahui.top`访问到Sshwifty，我也不清楚哪里出了问题，最终还是来请教作者了。
![](https://image.xingjiahui.top/blog/20200510210946.png)
![](https://image.xingjiahui.top/blog/20200510211013.png)
![](https://image.xingjiahui.top/blog/20200510210652.png)
![](https://image.xingjiahui.top/blog/20200510210805.png)
（我是小白，作者轻喷，哈哈，真的好想用自己的域名访问到自己服务器上的Sshwifty）

**Comment by niruix** [comment]
呵呵，这就是为什么我在 https://github.com/niruix/sshwifty/issues/21#issuecomment-626265129 结尾的位置写了你可以去掉`HostName`设置里的东西。因为当`HostName`不为空时，Sshwifty会用其中的值来验证主机名。如果你访问的时候不是通过`HostName`中设定的主机名，则Sshwifty后端会拒绝你的访问。

另外，你需要将

    listen ..... # 服务器的设置，这里省略，用你自己的就好
    
这一行改成你[*原先服务器的那几行配置*](https://github.com/niruix/sshwifty/issues/21#issuecomment-626179282)，包括`listen`, `server_name`和`ssl_`之类。那一部分设置是不需要变更的，因此我在后面的答复里就没有引用了。

还有：

1. 你应该在Sshwifty后端的配置里去掉TLS相关的设置，让Sshwifty运行在HTTP模式下。TLS这部分应该让Nginx去处理，就像你原先Nginx里写的配置一样。
2. 如果你服务器的配置和条件许可的话，把Sshwifty的`ListenInterface`改成`127.0.0.1`可以避免潜在的安全问题。详情请看一下 https://github.com/niruix/sshwifty/issues/21#issuecomment-626265129

简单的说，就是你最后配置成这样：

    [你的浏览器] -------> [你服务器上的Nginx，HTTP/HTTPS] -------> [Sshwifty后端，HTTP]

**Comment by niruix** [comment]
另外，在你 https://github.com/niruix/sshwifty/issues/21#issuecomment-626326737 给出的截图里，`server 0.0.0.0:8182`这个地址是不合法的。

如果你的Sshwifty实例与Nginx是运行在同一台服务器上的，并且可以通过`127.0.0.1`访问的话，填写`server 127.0.0.1:8182`就可以了。否则你的操作系统需要将`0.0.0.0`自动转换成`127.0.0.1`。

**Comment by xingjiahui** [comment]
好的，感谢作者的回复，我去尝试修改！
