### ISSUE TITLE
Can not login when I am using a key with passphase

### ISSUE THREAD

**Issue by 2498981627** [niruix/sshwifty#22]
When login the server that private key has passphase, the pasge won't ask for passphase but tell you that 'no key found'.

**Comment by niruix** [comment]
Yes, currently the software does not accept encrypted private key which is a security measure explained in #7.

In short, I'm not very confident about browser safety when it comes to handling anything related to credentials.

In the meantime, could you please decrypt those keys manually before upload them? You can do so by following the description beneath the key upload box.

_Sent from my motorola one power using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by 2498981627** [comment]
Fine, I'll try so later.
By the way, this is really a nice project, hope you can insist.👍

**Comment by niruix** [comment]
Glad you like it 😊

**Comment by niruix** [comment]
Glad you like it 😊

**Comment by niruix** [comment]
Glad you like it 😊
