### ISSUE TITLE
谢谢大神~咋部署到heroku上面啊，用预编译文件git上去失败了......

### ISSUE THREAD

**Issue by null12138** [niruix/sshwifty#23]
求助~
是要改一些配置吗~
萌新，不懂........
谢谢大神~

**Comment by niruix** [comment]
如果你使用预编译的话，需要确保你本地能够能完整无错的编译出Sshwifty的二进制程序才行。

而Heroku支持Docker部署，Sshwifty也提供了Dockerfile，因此其实你可以通过容器方式进行部署，让Heroku去远程构建。这样一来，你只需要安装一个Heroku命令行，用它把部署模式换成Docker就行了。大致就像这里第三段说的：https://github.com/niruix/sshwifty/issues/5#issuecomment-532445656

**Comment by null12138** [comment]
谢谢大神~
可是我这里按照步骤部署时，出现了这个错误
|-(0) found 1 low severity vulnerability
|-(0)   run `npm audit fix` to fix them, or `npm audit` for details
|-(0)!info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz
|-(0)!  ✔ gifsicle pre-build test passed successfully
|-(0)!  ✔ jpegtran pre-build test passed successfully
|-(0)!  ✔ optipng pre-build test passed successfully
|-(0)!  ✔ pngquant pre-build test passed successfully
|-(0)!npm WARN sshwifty-ui@0.0.0 No repository field.
|-(0)!npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/watchpack/node_modules/fsevents):
|-(0)!npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
|-(0)!npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
|-(0)!npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
|-(0)!

**Comment by niruix** [comment]
你可以看一下部署是否成功了。如果成功了的话，上面的警告是可以忽略的。

另外那个“low severity vulnerability”并不会影响这个程序的安全性，因为受到影响的组件`minimist`只在是在构建favicon的过程中用到。

**Comment by null12138** [comment]
嗯嗯，好的，谢谢老板~明白了~
可是.......部署没成功.....报错了......
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
啊啊啊，本人是个小白啊，真的很感激~谢谢大神~

**Comment by niruix** [comment]
你可以去Heroku的后台看一下构建和部署日志。

    Browserslist: caniuse-lite is outdated. Please run next command npm update

说的只是`caniuse-lite`已经过期了，但是用旧版本不会影响构建。我这边会一直使用最新的依赖，但是如果依赖的依赖没有更新，我没有办法阻止由此产生的构建警告。

**Comment by null12138** [comment]
呃，大神，我这步以后就卡住了，然后半小时以后又自动重新开始上面remote的内容，三小时了，一直在循环...

**Comment by niruix** [comment]
那很奇怪。

你可不可以试一试用干净的代码重新构建一下呢？就是说，你那边重新下载这个项目的代码，然后用新的代码去让Heroku构建。

另外如果方便的话，请提供一下最后的构建日志，这样我也方便检查问题。最好能提供*至少最后1000行*吧。

Demo那个程序的部署过程和文件跟现在仓库里的代码是一样的。理论上不需要任何配置，因为需要设置的部分都已经设置好了，直接下载代码、装好Heroku的cli，把部署模式改成Container，然后`git push heroku master`就行了。

BTW: 如果你的部署成功了，你需要手动去Heroku后台添加一个环境变量，可以参考下https://github.com/niruix/sshwifty/issues/5#issuecomment-532445656 里面提到的。不过这是你等部署成功之后才需要做的。

**Comment by null12138** [comment]
哇⊙∀⊙！
谢谢大神啦~
我刚才重新git clone下来一次，又重试了一次，成功啦😃不知道之前怎么回事😂
谢谢大神~

**Comment by niruix** [comment]
可能是之前你尝试手动Generate的时候，产生了一些临时的代码，而之后因为部署方式变更了，那些临时代码与新的部署方式不匹配，因而引发了错误。

现在问题解决了就好。我这边就先把这个Issue关闭了。如果你发现这个问题实际并没有解决，请重新打开。
