### ISSUE TITLE
hello, an error when I click the Authenticate button.

### ISSUE THREAD

**Issue by jackjieYYY** [niruix/sshwifty#24]
I am using the Binary file: sshwifty_0.2.3-beta-release_linux_amd64.tar.gz and running on Debian 10.

please have a check, thanks!

![1](https://user-images.githubusercontent.com/53422254/87221973-6805e300-c3b3-11ea-86c8-7542fb46eab7.png)

**Comment by niruix** [comment]
I think the primary cause (that I know of) of the problem has already been explained in [README.md](https://github.com/niruix/sshwifty/blob/6cd93a54572d7df6d0ac561a7d491f616549f808/README.md#why-i-got-error-typeerror-cannot-read-property-importkey-of-undefined). 

Have you tried to resolve the problem base on the information inside the README?

**Comment by jackjieYYY** [comment]
hello, Thanks for your reply. here is the same error when I using the Docker version.

$ docker run --detach \
  --restart=always \
  --publish 8182:8182 \
  --name sshwifty \
  niruix/sshwifty:latest

and this is the screenshot:


![1](https://user-images.githubusercontent.com/53422254/87222482-35f68000-c3b7-11ea-9b4e-dcbfda23d27a.png)


and about the README I would read again.

thank you anyway.

**Comment by jackjieYYY** [comment]
> I think the primary cause (that I know of) of the problem has already been explained in [README.md](https://github.com/niruix/sshwifty/blob/6cd93a54572d7df6d0ac561a7d491f616549f808/README.md#why-i-got-error-typeerror-cannot-read-property-importkey-of-undefined).
> 
> Have you tried to resolve the problem base on the information inside the README?


Why I got error "TypeError: Cannot read property 'importKey' of undefined"
It's usually because your web browser does not support WebCrypt API, or the support has been disabled.

If you're using Google Chrome, please connect Sshwifty with HTTPS. Chrome will disable WebCrypt and many other APIs when the connection is not safe.



Thank you, I would try to use https.

**Comment by niruix** [comment]
Yeah, I saw that you're using Chrome and the connection was "Insecure". Which is the exact scenario described in the README.

To put it simple, the solution *should be* simply enable HTTPS. You can refer other sections in the README to learn how.

**Comment by jackjieYYY** [comment]
> Yeah, I saw that you're using Chrome and the connection was "Insecure". Which is the exact scenario described in the README.
> 
> To put it simple, the solution _should be_ simply enable HTTPS. You can refer other sections in the README to learn how.

大佬牛逼 不愧是大佬
