### ISSUE TITLE
Optionally remove red notice "An insecured service may steal your secrets. Always exam the safety of the service before using it."

### ISSUE THREAD

**Issue by moshix** [niruix/sshwifty#27]
Can it be made a config option to remove the red statement saying "An insecured service may steal your secrets. Always exam the safety of the service before using it."?

It's very distracting and unpleasing to the eye. 

thanks

**Comment by niruix** [comment]
Short answer is no. The web UI is pre-rendered during the build process, it cannot be changed after the software is built to binary. Also, the message is simply telling the truth: Software like this is really in fact less secure than a program statically installed on your computer. Users need to aware of that.

Of course, there is a longer answer: The code it self can be changed. The related file is [connect.vue](https://github.com/niruix/sshwifty/blob/67c99e3092abbae009b711ce5d4ea64d9cfebd00/ui/widgets/connect.vue#L59), simply remove the `<div>ision` id'd `connect-warning` should remove the message. And then you need to rebuild the software (via `npm run build` command) of course.

But that also means you need to maintain your own fork for the change :)

**Comment by niruix** [comment]
Closing this issue. Sorry, for not making you happy :(

**Comment by CJendantix** [comment]
@moshix I am actually doing this. https://github.com/CJendantix/sshwifty-nowarning

**Comment by nirui** [comment]
> @moshix I am actually doing this. https://github.com/CJendantix/sshwifty-nowarning

Thanks!

I can't remove the warning because it's not feel right on my part. But users can modify the software however they want after they got the code.

**Comment by nirui** [comment]
> @moshix I am actually doing this. https://github.com/CJendantix/sshwifty-nowarning

Thanks!

I can't remove the warning because it's not feel right on my part. But users can modify the software however they want after they got the code.

**Comment by nirui** [comment]
Sorry for the bothering. But hi @CJendantix, I received an email notification about a pull request (number 121) from what appears to be another account of yours. But pull request has since disappeared along with the said account, and as result, I cannot access the pull request at this moment.

I just want to let you know that if it's a valid pull request for a grammar fix, I'll handle it after it reappears. Thanks!

**Comment by CJendantix** [comment]
I'm trying to get more used to github and contributing more to the repos I use. Thank you for maintaining this repo, it's really awesome.

**Comment by CJendantix** [comment]
And while we're on the topic, have you tried to learn Rust, it's a great language that I'm trying to learn.
