### ISSUE TITLE
预设能否一键连接

### ISSUE THREAD

**Issue by loveqianool** [niruix/sshwifty#28]
现在预设好了还是要点四步才能连接，能否跟最近连接一样点击即连接？

还有配置文件的私钥能不能使用文件路径配置，如
```
"Private Key": "/id_rsa_nopass"
```
十几个服务器配置文件拉的老长，全都是私钥内容。

或者使用环境变量预先配置，如
```
-e PrivateKey1="-----BEGIN RSA PRIV...\nMIIE...\n-----END RSA PRI...\n"
```
然后配置文件直接
```
"Private Key": "PrivateKey1"
```
私钥其实没几个，大多服务器都是用的同一个私钥，现在配置文件大多都是重复内容。

**Comment by niruix** [comment]
你好，

就软件现在的设计，要实现一点即连比较困难。因为：首先，预设功能其实只是在自动填写表单，代码和流程与手动填写表单是一致的；其次，让用户手动进行完成连接流程，也可以给用户一个确认输入的机会。而且，一旦用户完成了连接，“Known Remotes”列表上就会出现刚才连接的客户端项了，用户可以点击该项来进行后续的连接，在实际情况下大多数时候用户只需要使用一次预设即可。

关于从文件加载预设值的功能，这个正在实现。方案类似于你提到的 `"Private Key": "/id_rsa_nopass"`，只是增加了前缀，即：

- 当配置值无前缀时，配置值是值本身（即原先的方式）；
- 当配置值包含“file://”前缀，如`file:///tmp/pubkey`时，则从文件`/tmp/pubkey`加载配置值的内容。

这样可以在解决配置文件过大问题的同时避免破坏配置文件的兼容性。

**Comment by loveqianool** [comment]
好的，谢谢你。
