### ISSUE TITLE
复制与粘贴快捷键

### ISSUE THREAD

**Issue by loveqianool** [niruix/sshwifty#29]
复制与粘贴能不能再绑定 Ctrl Insert 复制，Shift Insert 粘贴，这个快捷键比较通用。

现在复制可以使用，但是粘贴不起作用。
我在 chrome 86 上测试，使用 Ctrl Shift V 粘贴，它只是回显了命令，但是不能执行。

**Comment by niruix** [comment]
你好，

Shift+Insert和Ctrl+Insert已经加入，并会随着下一个版本发布。

另外粘贴只有回显的问题确实是一个Bug，所粘贴的数据并没有发送到远程。这个问题也已经修好了，会随着下一个版本发布。

目前代码都在`dev`分支。

**Comment by niruix** [comment]
新版本`0.2.5-beta-release`已经发布了，包含上述问题的修复以及 #28 所提到的关于配置文件的改进（即支持`file://`和`enviroment://`特殊前缀，请参考[README.md](https://github.com/niruix/sshwifty#configuration-file)里的说明）。

谢谢你的意见 :)
