### ISSUE TITLE
在已知远程那里显示自定义的服务器名称

### ISSUE THREAD

**Issue by loveqianool** [niruix/sshwifty#6]
都是使用 ip 连的，多了之后经常不知道哪个是哪个。

**Comment by niruix** [comment]
是不是可以用域名而不是IP进行连接？

我看了一下Address book（Known remotes），感觉按照目前的设计，这个功能比较难达成 :(

**Comment by loveqianool** [comment]
好吧，小问题，只是很多时候懒得去解析 :)
