### ISSUE TITLE
[Docker Build] Unable to connect to the Sshwifty backend server: 

### ISSUE THREAD

**Issue by kalzi** [niruix/sshwifty#8]
Hi,

Thank you so much for this beautiful implementation.. Great Work.

After trying the Heroku URL, i wanted to build this project on my system and hence I cloned the project and used the available Dockerfile (No changes to any files) and issued `docker build -t ssh .` at the root of the project.

The build seemed to be successful, however launching the container using 
```
docker run --detach \
  --restart=always \
  --publish 8182:8182 \
  --name sshwifty \
  ssh

aa9d179b9a95180d4c9d4822b7b7e4ef8b01eb50e75c2a3e3427fd4e27504d6e
```

When I browse to IP:8182 , i could see the FrontEnd page available, however when I navigate to + > SSH (or) Telnet, i receive a browser pop up as indicated below

```
Unable to connect to the Sshwifty backend server: TypeError: Cannot read property 'importKey' of undefined
```
You see any wrong doing on my actions? Kindly advise if this can fixed/corrected.

**Comment by kalzi** [comment]
Well, After reading the README carefully, i see that this is a known issue and you suggested to switch browser or to HTTPS.. 

My bad for jumping the gun.. Keep up your good work! Thanks again for sharing.

**Comment by niruix** [comment]
I don't even have a chance to respond. Glad you've resolved the problem pal :)

**Comment by IIIdefconIII** [comment]
> Well, After reading the README carefully, i see that this is a known issue and you suggested to switch browser or to HTTPS.. 
> 
> My bad for jumping the gun.. Keep up your good work! Thanks again for sharing.

Can you share how you fixed it? Ty

**Comment by nirui** [comment]
Hi, @IIIdefconIII, probably this: https://github.com/nirui/sshwifty#why-i-got-error-typeerror-cannot-read-property-importkey-of-undefined, or to put it into short words: setup HTTPS for Sshwifty.

**Comment by IIIdefconIII** [comment]
Thanks for the Quick response, I put it behind cloudflare watch has httpps and works perfect


Met vriendelijke groet,

________________________ _______________________
Thomas van Dalen

E: ***@***.******@***.***>

T: +316 30 929 009

________________________________

**Comment by nirui** [comment]
Hi @IIIdefconIII, can you describe a little bit more about the problem? Error message, log output, which browser used etc and other information that might help debugging the issue?

**Comment by IIIdefconIII** [comment]
It didn't find the server. But j guess cause it's was on http, I put it behind clouflare now on https and it seems to work


Met vriendelijke groet,

________________________ _______________________
Thomas van Dalen

E: ***@***.******@***.***>

T: +316 30 929 009

________________________________
