### ISSUE TITLE
布署到群晖的docker中连接的时候提示E1006错误

### ISSUE THREAD

**Issue by rainsuns** [niruix/sshwifty#9]
RT，点+创建SSH或telnet后，提示Unable to connect to the Sshwifty backend server: WebSocket Error (1006)

**Comment by niruix** [comment]
WebSocket错误1006表示链接异常关闭。

你的连接有没有通过中间层？比如Nginx反向代理之类。

如果有的话，可能需要检查一下Nginx的配置，允许它反向代理Websocket请求；如果是直接连接，没有中间层，则可能是因为服务器主动断开了你的客户端。如果是这样，建议首先看看运行Sshwifty服务端的机器与进行访问的客户端之间有没有时间差，因为Sshwifty的Websocket协议是时间敏感的，时间差可能会让服务器认为客户端是非法的。

你可以看一下Docker日志，`docker logs <运行Sshwifty的容器>`。如果有“cipher authentication”之类的警告，那么大体是因为时间差导致的，你可以用`ntp`同步一下两台机器的时间。

当然，也有可能是访问密码错了。如果是这样，一般刷新一下页面就行了。

**Comment by rainsuns** [comment]
确实用了反代，改下配置可以用了，比用GateOne舒服多了，感谢大佬。
配置如下，群晖中登陆root用户，编辑/etc/nginx/app.d/server.ReverseProxy.conf文件，添加以下两段，然后保存退出。执行nginx -s reload命令，给有需要的人

`map $http_upgrade $connection_upgrade {
        default upgrade;
            '' close;
}`



`proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;`

**Comment by raining1123** [comment]
> 确实用了反代，改下配置可以用了，比用GateOne舒服多了，感谢大佬。
> 配置如下，群晖中登陆root用户，编辑/etc/nginx/app.d/server.ReverseProxy.conf文件，添加以下两段，然后保存退出。执行nginx -s reload命令，给有需要的人
> 
> `map $http_upgrade $connection_upgrade { default upgrade; '' close; }`
> 
> `proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection $connection_upgrade;`

老哥，我把您自己的教程图转发过来了 嘻嘻嘻
https://aichh.com/507.html

![image](https://user-images.githubusercontent.com/17892238/75952329-65691d80-5ee9-11ea-9c97-8dea083e388a.png)

**Comment by waylonwang** [comment]
不用那么麻烦，在群晖的反代中直接添加自定义标题就可以了

<img width="536" alt="屏幕快照 2022-09-18 上午11 11 35" src="https://user-images.githubusercontent.com/7424276/190884022-7c94708f-91c7-4fdb-9224-a7ccc1257d21.png">

**Comment by cubale** [comment]
> 不用那么麻烦，在群晖的反代中直接添加自定义标题就可以了
> 
> <img alt="屏幕快照 2022-09-18 上午11 11 35" width="536" src="https://user-images.githubusercontent.com/7424276/190884022-7c94708f-91c7-4fdb-9224-a7ccc1257d21.png">

非常感谢，成功解决了我的问题
